cart/urls.py
from django.urls import path
from . import views


app_name ="cart"


urlpatterns =[
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:id>/',views.cart_add, name='cart_add'),
    path('remove/<int:id>/', views.cart_remove, name='cart_remove'),


]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('take/', views.take, name='take'),


    path('payment/', views.payment, name='payment'),
    path('result/', views.result, name='result'),
    path('success/', views.success, name='success'),
    path('failure/', views.fail, name='failure'),
]

uraz/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from django.conf.urls.i18n import i18n_patterns
from yoga import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('cart/',include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls',namespace='orders')),
    path('shop/',include('shop.urls', namespace='shop')),
    path('user/',include("user.urls")),
    path('blog/',include('yoga.urls')),
    path('sss/',views.sss,name='sss',),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('<str:slug>/',views.blog_detail,name='blog_detail'),
    #path('zeynep/',include("yoga.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns  += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import  forms




PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1,5)]



class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int,label="")
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from django.contrib.auth.decorators import login_required

@require_POST
def cart_add(request, id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=id)
    cart.remove(product)
    return redirect('cart:cart_detail')



@login_required(login_url="user:login")
def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% load static %}

{% block seo %}
<title>Shop</title>

{% endblock %}
{% block content %}

{% if cart|length > 0.9 %}

  <section class="page-title centred">
            <div class="pattern-layer" style="background-image: url({% static 'assets/images/background/page-title.jpg' %});"></div>
            <div class="auto-container">
                <div class="content-box">
                    <h1>Sepetim</h1>
                </div>
            </div>
        </section>
        <!-- page-title end -->


        <!-- cart section -->
        <section class="cart-section cart-page">
            <div class="auto-container">
                <div class="row clearfix">
                    <div class="col-lg-12 col-md-12 col-sm-12 table-column">
                        <div class="table-outer">
                            <table class="cart-table">
                                <thead class="cart-header">
                                    <tr>
                                        <th>&nbsp;</th>
                                        <th class="prod-column">Ürün İsmi</th>
                                        <th>&nbsp;</th>
                                        <th>&nbsp;</th>
                                        <th class="price">Fiyat</th>
                                        <th class="quantity">Miktar</th>
                                        <th>Toplam</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for item in cart %}
                                    {% with product=item.product %}
                                        <tr>
                                        <td colspan="4" class="prod-column">
                                            <div class="column-box">
                                                <div class="remove-btn">
                                                   <a style="color:red;" href="{% url 'cart:cart_remove' product.id %}"><i class="flaticon-close"></i></a>
                                                </div>
                                                <div class="prod-thumb">
                                                    <a href="#"><img src="{% if product.image %}{{ product.image.url }}{% else %}{% endif %}" alt=""></a>
                                                </div>
                                                <div class="prod-title">
                                                    {{product.name}}
                                                </div>
                                            </div>
                                        </td>
                                        <td class="price">₺ {{product.price}}</td>
                                        <td class="qty">
                                            <form class="container" action="{% url 'cart:cart_add' product.id %}" method="post">
                                              <div class="row">
                                                  <div class="col-6">{{ item.update_quantity_form.quantity |as_crispy_field }}</div>
                                                  <div ><button class="btn btn-dark btn-xs mee" type="submit" value="Değiştir">Güncelle</button></div>
                                                  <div>{{ item.update_quantity_form.update}}</div>
                                              </div>
                                              {% csrf_token %}
                                          </form>
                                        </td>
                                        <td class="sub-total">₺ {{ item.total_price }}</td>
                                    </tr>
                                    {% endwith %}
                                {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <br>
                <br>
                <br>
                <div class="cart-total">
                    <div class="row">
                        <div class="col-xl-5 col-lg-12 col-md-12 offset-xl-7 cart-column">
                            <div class="total-cart-box clearfix">
                                <h4>Genel Toplam</h4>
                                <ul class="list clearfix">
                                    <li>Toplam(KDV Dahil):<span>₺  {{ cart.get_total_price }}</span></li>
                                </ul>
                                <a href="{% url 'orders:order_create' %}" class="theme-btn-two">Sepeti Onayla<i class="flaticon-right-1"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>






{% else %}
<br>
<br>
<br>
<section class="section-small text-center" id="services">
      <div class="container">
        <div class="row">
            <p><a class="button btn btn-dark" href="/shop/dersler/">Hadi Gel Ürünlerimize Bakalım</a></p>
        </div>
      </div>
    </section>
{% endif %}
{% endblock %}
 <section class="cart-section cart-page">
            <div class="auto-container">
                <div class="row clearfix">
                    <div class="col-lg-12 col-md-12 col-sm-12 table-column">
                        <div class="table-outer">
                            <table class="cart-table">
                                <thead class="cart-header">
                                    <tr>
                                        <th>&nbsp;</th>
                                        <th class="prod-column">Ürün İSmi</th>
                                        <th>&nbsp;</th>
                                        <th>&nbsp;</th>
                                        <th class="price">Fiyat</th>
                                        <th class="quantity">Adet</th>
                                        <th>Toplam</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for item in cart %}
                                    {% with product=item.product %}
                                    <tr>
                                        <td colspan="4" class="prod-column">
                                            <div class="column-box">
                                                <div class="remove-btn">
                                                    <i class="flaticon-close"></i>
                                                </div>
                                                <div class="prod-thumb">
                                                    <a href=""><img src="{% if product.image %}{{ product.image.url }}{% else %}{% endif %}" alt=""></a>
                                                </div>
                                                <div class="prod-title">
                                                    {{product.name}}
                                                </div>
                                            </div>
                                        </td>
                                        <td class="price">₺ {{product.price}}</td>
                                        <td class="qty">
                                            <form class="container" action="{% url 'cart:cart_add' product.id %}" method="post">
                                              <div class="row">
                                                  <div class="col-6">{{ item.update_quantity_form.quantity |as_crispy_field }}</div>
                                                  <div ><button class="btn btn-dark btn-xs mee" type="submit" value="Değiştir"><i class="fas fa-undo-alt"></i></button></div>
                                                  <div>{{ item.update_quantity_form.update}}</div>
                                              </div>
                                              {% csrf_token %}
                                          </form>
                                        </td>
                                        <td class="sub-total">₺ {{ item.total_price }}</td>
                                    </tr>
                                  {% endwith %}
                                {% endfor %}
                                    <tr>
                                        <td colspan="4" class="prod-column">
                                            <div class="column-box">
                                                <div class="remove-btn">
                                                    <i class="flaticon-close"></i>
                                                </div>
                                                <div class="prod-thumb">
                                                    <a href="#"><img src="assets/images/resource/shop/cart-2.jpg" alt=""></a>
                                                </div>
                                                <div class="prod-title">
                                                    Girls Print Tops
                                                </div>
                                            </div>
                                        </td>
                                        <td class="price">$50.00</td>
                                        <td class="qty">
                                            <div class="item-quantity">
                                                <input class="quantity-spinner" type="text" value="1" name="quantity">
                                            </div>
                                        </td>
                                        <td class="sub-total">$50.00</td>
                                    </tr>
                                    <tr>
                                        <td colspan="4" class="prod-column">
                                            <div class="column-box">
                                                <div class="remove-btn">
                                                    <i class="flaticon-close"></i>
                                                </div>
                                                <div class="prod-thumb">
                                                    <a href="#"><img src="assets/images/resource/shop/cart-3.jpg" alt=""></a>
                                                </div>
                                                <div class="prod-title">
                                                    Baby Backpacks
                                                </div>
                                            </div>
                                        </td>
                                        <td class="price">$70.00</td>
                                        <td class="qty">
                                            <div class="item-quantity">
                                                <input class="quantity-spinner" type="text" value="1" name="quantity">
                                            </div>
                                        </td>
                                        <td class="sub-total">$70.00</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="othre-content clearfix">
                    <div class="coupon-box pull-left clearfix">
                        <input type="text" placeholder="Enter coupon code...">
                        <button type="submit" class="theme-btn-two">Apply coupon<i class="flaticon-right-1"></i></button>
                    </div>
                    <div class="update-btn pull-right">
                        <button type="submit" class="theme-btn-one">Update Cart<i class="flaticon-right-1"></i></button>
                    </div>
                </div>
                <div class="cart-total">
                    <div class="row">
                        <div class="col-xl-5 col-lg-12 col-md-12 offset-xl-7 cart-column">
                            <div class="total-cart-box clearfix">
                                <h4>Cart Totals</h4>
                                <ul class="list clearfix">
                                    <li>Subtotal:<span>$150</span></li>
                                    <li>Order Total:<span>$150</span></li>
                                </ul>
                                <a href="cart.html" class="theme-btn-two">Proceed to Checkout<i class="flaticon-right-1"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>