cart/urls.py
from django.urls import path
from . import views


app_name ="cart"


urlpatterns =[
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:id>/',views.cart_add, name='cart_add'),
    path('remove/<int:id>/', views.cart_remove, name='cart_remove'),


]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('take/', views.take, name='take'),


    path('payment/', views.payment, name='payment'),
    path('result/', views.result, name='result'),
    path('success/', views.success, name='success'),
    path('failure/', views.fail, name='failure'),
]

uraz/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from django.conf.urls.i18n import i18n_patterns
from yoga import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('cart/',include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls',namespace='orders')),
    path('shop/',include('shop.urls', namespace='shop')),
    path('user/',include("user.urls")),
    path('blog/',include('yoga.urls')),
    path('sss/',views.sss,name='sss',),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('<str:slug>/',views.blog_detail,name='blog_detail'),
    #path('zeynep/',include("yoga.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns  += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from django import forms
from django.forms import SelectDateWidget

from shop.models import Product
from django.urls import reverse
import datetime
from django.contrib.auth.models import User




class Order(models.Model):
    first_name = models.CharField(max_length=50,verbose_name="İsim:")
    last_name = models.CharField(max_length=50,verbose_name="Soy İsim:")
    email = models.EmailField(verbose_name="Email Adresiniz:",default="")
    phone = models.CharField(max_length=11,verbose_name="Telefon :")
    tc = models.CharField(max_length=11,verbose_name="Tc No:")
    city = models.CharField(max_length=100,verbose_name="İl :")
    adress = models.CharField(max_length=100,verbose_name="Adres :")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    uniqid = models.CharField(max_length=11,verbose_name="Uniq id:")



    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())



class OrderItem(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, default="Alan")
    order = models.ForeignKey(Order, related_name='items', on_delete = models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete = models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    created_date = models.DateTimeField(auto_now=True, verbose_name="Oluşturlma Tarihi")
    tokenCheck = models.CharField(max_length=36,verbose_name="Token check:", null=False, default=False)
    paid = models.BooleanField(default=False)



    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity







class Reservation(models.Model):
    name = models.CharField(max_length=100, db_index=True, default='Name',null=True,blank=True)
    lastname = models.CharField(max_length=100, db_index=True, default='Lastname',null=True,blank=True)
    tc =models.CharField(max_length=100, db_index=True, default='TC',null=True,blank=True)
    email = models.CharField(max_length=100, db_index=True, default='Email',null=True,blank=True)
    phone =models.CharField(max_length=100, db_index=True, default='Phone',null=True,blank=True)
    city = models.CharField(max_length=100, db_index=True, default='City',null=True)
    adres = models.CharField(max_length=100, db_index=True, default='Adress', null=True)
    email = models.CharField(max_length=100, db_index=True, default='Mail',null=True)
    price = models.CharField(max_length=100, db_index=True, default='Price', null=True)
    tokenCheck = models.CharField(max_length=50, verbose_name="Token check:", null=False, default=False)
    cardHolderName = models.CharField(max_length=100, db_index=True, default='KK Sahibi',null=True,blank=True)
    cardNumber = models.CharField(max_length=100, db_index=True, default='KK Number',null=True,blank=True)
    expireMonth = models.CharField(max_length=100, db_index=True, default='Ay',null=True,blank=True)
    expireYear = models.CharField(max_length=100, db_index=True, default='Yıl',null=True,blank=True)
    cvc = models.CharField(max_length=100, db_index=True, default='CVC',null=True,blank=True)
    paid = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.phone



class ReturnData(models.Model):
    status = models.CharField(max_length=510,verbose_name="status:")
    systemtime = models.CharField(max_length=510,verbose_name="systemtime:")
    conversationİd = models.CharField(max_length=510,verbose_name="conversationİd:")
    price =  models.CharField(max_length=510,verbose_name="price:")
    paidPrice = models.CharField(max_length=510,verbose_name="paidPrice:")
    paymentid = models.CharField(max_length=510,verbose_name="paymentid:")
    binNumber = models.CharField(max_length=510,verbose_name="binNumber:")
    result_token = models.CharField(max_length=510,verbose_name="result_token:")
    payment_token = models.CharField(max_length=510,verbose_name="payment_token:")


    def __str__(self):
        return self.status



class WebhookData(models.Model):
    paymentConversation = models.CharField(max_length=510,verbose_name="paymentConversation:")
    merchant = models.CharField(max_length=510,verbose_name="merchant:")
    webhooktoken = models.CharField(max_length=510,verbose_name="webhooktoken:")
    status = models.CharField(max_length=510,verbose_name="status:")
    iyziReferenceCode = models.CharField(max_length=510,verbose_name="iyziReferenceCode:")
    iyziEventType = models.CharField(max_length=510,verbose_name="iyziEventType:")
    iyziEventTime =models.CharField(max_length=510,verbose_name="iyziEventTime:")


    def __str__(self):
        return self.status



class UserTokenData(models.Model):
    userlast = models.CharField(max_length=510)
    usertoken = models.CharField(max_length=510)


    def __str__(self):
        return self.usertoken

orders/forms.py
from django import forms

from .models import Order
import datetime


class OrderCreateForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'phone', 'email','city','tc','adress']




orders/views.py
from django.shortcuts import render, redirect
from .models import OrderItem, Order, Reservation, WebhookData, UserTokenData
from .forms import OrderCreateForm
from cart.cart import Cart
import time
from django.contrib.auth.models import User
from django.contrib import messages
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from shop.models import Category, Product

# iyzico modülü -> pip install iyzipay
import iyzipay

from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.http import require_http_methods, require_POST
from django.views.decorators.csrf import csrf_exempt
import requests
import json
from django.db.models import Q

# Bu verileri, admin panelinden eklenebilir yapacağız

api_key = 'sandbox-etkBOaBAec7Zh6jLDL59Gng0xJV2o1tV'
secret_key = 'sandbox-uC9ysXfBn2syo7ZMOW2ywhYoc9z9hTHh'
base_url = 'sandbox-api.iyzipay.com'


options = {
    'api_key': api_key,
    'secret_key': secret_key,
    'base_url': base_url
    }
sozlukToken = list()




@login_required(login_url="user:login")
def order_create(request):
    cart = Cart(request)


    for c in cart:
        print(c)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.author=request.user
            order.save()



            #messages.success(request, "Rezervasyonunuz Oluşturuldu, En Yakın Zaman Size Ulaşıcağız.")
            #subject = "!!!Sipariş!!!"
            #from_email = settings.EMAIL_HOST_USER
            #to_email = [from_email, "tercuman4848@gmail.com"]
            #signup_message = "!!!!Müşteri Siparişi!!!"
            #send_mail(subject=subject, from_email=from_email, recipient_list=to_email, message=signup_message,
                      #fail_silently=True)

            for item in cart:
                 newItem = OrderItem.objects.create(order=order,author=request.user,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'],
                                         )
                 #newItem.product.stock = newItem.product.stock - item['quantity']
                 newItem.product.save()
            # clear the cart
            #cart.clear()
            #return payment(request)
            return redirect('/order/take')
    else:
        form = OrderCreateForm()
    return render(request, 'orders/order/create.html', {'cart': cart,
                                                        'form': form,
                                                        })

@login_required(login_url="user:login")
def take(request):

    cart = Cart(request)
    """
    jet = Category.objects.filter(name__contains='jet')
    fly = Category.objects.filter(name__contains='fly')
    tur = Category.objects.filter(name__contains='turlar')
    adre = Category.objects.filter(name__contains='adrenalin')
    korsan = Category.objects.filter(name__contains='tekne')
    """
    #show = OrderItem.objects.filter(Q(author=request.user) and Q(paid=False)).order_by('-id')

    #a = OrderItem.objects.all()
    #total = int()
    #for i in a:
        #print(i.order)
        #print(i.price)
        #total += float(i.price)

    #print(total)


    context = {
        #"show": show,
        "cart" : cart
    }
    #'jet':jet,'fly':fly,'tur':tur,'adre':adre,'korsan':korsan, 'success': 'Ödeme Alındı'
    return render(request,"orders/order/take.html",context)


@require_http_methods(['POST'])
@csrf_exempt
def payment(request):
    cart = Cart(request)

    if 'btnSubmit' in request.POST:
        #print(request.POST)
        if True:
            price = request.POST.get('price')
            name = request.POST.get('name')
            lastname = request.POST.get('lastname')
            tc = request.POST.get('tc')
            email = request.POST.get('email')
            phone = request.POST.get('phone')
            city = request.POST.get('city')
            adres = request.POST.get('adres')
            tokenCheck = request.POST.get('tokenCheck')
            cardHolderName = request.POST.get('cardHolderName')
            print('NAME',cardHolderName)
            cardNumber = request.POST.get('cardNumber')
            expireMonth = request.POST.get('expireMonth')
            expireYear = request.POST.get('expireYear')
            cvc = request.POST.get('cvc')






    payment_card = {
        'cardHolderName': str(cardHolderName),
        'cardNumber': str(cardNumber),
        'expireMonth': str(expireMonth),
        'expireYear': str(expireYear),
        'cvc': str(cvc),
        'registerCard': '0'
    }

    buyer = {
        'id': str(tc),
        'name': str(name),
        'surname': str(lastname),
        'gsmNumber': str(phone),
        'email': str(email),
        'identityNumber': '74300864791',
        'lastLoginDate': '2015-10-05 12:43:35',
        'registrationDate': '2013-04-21 15:12:09',
        'registrationAddress': str(adres),
        'ip': '85.34.78.112',
        'city': str(adres),
        'country': 'Turkey',
        'zipCode': '34732'
    }

    address = {
        'contactName': str(name),
        'city': str(adres),
        'country': 'Turkey',
        'address': str(adres),
        'zipCode': '34732'
    }

    basket_items = [
        {
            'id': 'BI101',
            'name': 'Binocular',
            'category1': 'Collectibles',
            'category2': 'Accessories',
            'itemType': 'PHYSICAL',
            'price': str(price)
        },

    ]

    request = {
        'locale': 'tr',
        'conversationId': str(tc),
        'price': str(price),
        'paidPrice': str(price),
        'currency': 'TRY',
        'installment': '1',
        'basketId': 'B67832',
        'paymentChannel': 'WEB',
        'paymentGroup': 'PRODUCT',
        'paymentCard': payment_card,
        'buyer': buyer,
        'shippingAddress': address,
        'billingAddress': address,
        'basketItems': basket_items
    }

    payment = iyzipay.Payment().create(request, options)

    check = payment.read().decode('utf-8')

    data = json.loads(check, object_pairs_hook=list)



    #print('''PAYMENT''',data)




    #print('''MANİN''',data[0][1],data[18][1])



    if data[0][1] == 'success':
        newRezervation = Reservation.objects.create(price=price,name=name,lastname=lastname,tc=tc,email=email,phone=phone,city=city,adres=adres,
         cardHolderName='K.K Kayıt Altına Alınmıyor', cardNumber='K.K Kayıt Altına Alınmıyor',
                                                    expireMonth='K.K Kayıt Altına Alınmıyor', expireYear=expireYear, cvc=cvc,
                                                    tokenCheck=data[18][1],paid=True)

        newRezervation.save()

        sendOrder = Reservation.objects.filter(Q(tc=data[3][1]) and Q(tokenCheck=data[18][1]))
        mail = ''
        emaill = ''

        for i in sendOrder:
            # print(i.product.description)
            mail += str(i.name) + '\n' + str(i.adres) + '\n' + '\n'
            thanks = 'Thank You, Your Payment Done :)'
            emaill = i.email
            isim = i.name



        info = 'Your reservation is complete.'
        footer = 'Your ticket information . Before the transfer, you can reach us 24/7 from our chatbot .'
        name = isim


        email = emaill
        subject = 'Payment successful'

        from_email = settings.EMAIL_HOST_USER
        to_email = [from_email, email, 'djangomarmaris@gmail.com']
        contact_message = "WWW.TRANSFERCİDEN.COM\n Ödeme Durumu   : %s\n İnfo :  %s\n----------------------\n Name :  %s\n Note :  %s" % (
            thanks,
            info,
            name,
            footer
        )
        send_mail(subject, contact_message, from_email, to_email, fail_silently=True)
        cart.clear()
        return redirect('/order/success/')

    else:
        newRezervation = Reservation.objects.create(price=price,name=name,lastname=lastname,tc=tc,email=email,phone=phone,city=city,adres=adres,
         cardHolderName='K.K Kayıt Altına Alınmıyor', cardNumber='K.K Kayıt Altına Alınmıyor',
                                                    expireMonth='K.K Kayıt Altına Alınmıyor', expireYear=expireYear, cvc=cvc,
                                                    tokenCheck='Ödeme Alınamacı Canım Benim',paid=False)

        newRezervation.save()


        return redirect('/order/failure/')

    return HttpResponse(status=200)


@require_http_methods(['POST'])
@csrf_exempt
def result(request):

    a = Reservation.objects.filter(Q(author_id=request.user.id) and Q(paid=False))
    total = int()
    orderID = list()
    for i in a:
        orderID.append(i.tc)


    print(orderID)

    kim = UserTokenData.objects.filter(userlast= str(i.tc)).order_by('id')
    son = kim.last()
    print('SON DENEME',son.usertoken)

    context = dict()
    mesaj = request
    url = request.META.get('')
    request = {
        'locale': 'tr',
        'conversationId': str(i.tc) , #sepetClock[0] 'tu
        'token': str(son.usertoken),
        }
    checkout_form_result = iyzipay.CheckoutForm().retrieve(request, options)
    print("************************")
    print(type(checkout_form_result))
    result = checkout_form_result.read().decode('utf-8')
    print("************************")
    #print(sozlukToken[0])   # Form oluşturulduğunda
    print("************************")
    print("************************")
    sonuc = json.loads(result, object_pairs_hook=list)
    #print(sonuc[0][1])  # İşlem sonuç Durumu dönüyor
    #print(sonuc[5][1])   # Test ödeme tutarı
    print("************************")
    for i in sonuc:
        print(i)


    #print(sozlukToken[0])
    print("************************")
    #print(sozlukToken)
    print("************************")

orders/templates/orders/order/create.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block seo %}
    <title>Ödeme Şeçenekleri</title>
{% endblock %}
{% block content %}






 <section class="checkout-section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-12 col-sm-12 left-column">
                        <div class="inner-box">
                            <div class="billing-info">
                                <h4 class="sub-title">Müşteri Bilgileri</h4>
                                <form action="{%  url 'orders:payment'  %}" method="post" class="billing-form">
                                    {% csrf_token %}
                                    <input type="text" name="price" hidden value="{{ cart.get_total_price }}">
                                    <div class="row">
                                        <div class="col-lg-6 col-md-6 col-sm-12 form-group">
                                            <label>İsim*</label>
                                            <div class="field-input">
                                                <input type="text" name="name">
                                            </div>
                                        </div>
                                        <div class="col-lg-6 col-md-6 col-sm-12 form-group">
                                            <label>Soyisim*</label>
                                            <div class="field-input">
                                                <input type="text" name="lastname">
                                            </div>
                                        </div>
                                        <div class="col-lg-12 col-md-12 col-sm-12 form-group">
                                            <label>Tc Bilgileriniz*</label>
                                            <div class="field-input">
                                                <input type="text" name="tc">
                                            </div>
                                        </div>
                                        <div class="col-lg-12 col-md-12 col-sm-12 form-group">
                                            <label>Email*</label>
                                            <div class="field-input">
                                                <input type="email" name="email">
                                            </div>
                                        </div>
                                        <div class="col-lg-6 col-md-6 col-sm-12 form-group">
                                            <label>Telefon Numarası*</label>
                                            <div class="field-input">
                                                <input type="text" name="phone">
                                            </div>
                                        </div>
                                        <div class="col-lg-6 col-md-6 col-sm-12 form-group">
                                            <label>Şehir*</label>
                                             <div class="field-input">
                                                <input type="text" name="city">
                                            </div>
                                        </div>
                                        <div class="col-lg-12 col-md-12 col-sm-12 form-group">
                                            <label>Address*</label>
                                            <div class="field-input">
                                                <input type="text" name="adress" class="address">
                                            </div>
                                        </div>
                                        <hr>
                                        <div class="col-lg-6 col-md-6 col-sm-12 form-group">
                                            <label>Kredi Kartı Bilgileri*</label>
                                            <div class="field-input">
                                                <input type="text" name="cardHolderName">
                                            </div>
                                        </div>
                                        <div class="col-lg-6 col-md-6 col-sm-12 form-group">
                                            <label>Kredi Kartı Numarası*</label>
                                            <div class="field-input">
                                                <input type="text" name="cardNumber">
                                            </div>
                                        </div>
                                      <div class="col-lg-4 col-md-4 col-sm-12 form-group">
                                            <label>Ay*</label>
                                            <div class="field-input">
                                                <input type="text" name="expireMonth">
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-4 col-sm-12 form-group">
                                            <label>Yıl*</label>
                                            <div class="field-input">
                                                <input type="text" name="expireYear">
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-4 col-sm-12 form-group">
                                            <label>CVC*</label>
                                            <div class="field-input">
                                                <input type="text" name="cvc">
                                            </div>
                                        </div>
                                        <div class="col-lg-6 col-md-3 col-sm-12 form-group">
                                            <div class="field-input">
                                                 <button name="btnSubmit" type="submit" class="theme-btn-two">Ödemeyi Bitir<i class="flaticon-right-1"></i></button>
                                            </div>
                                        </div>

                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-12 col-sm-12 right-column">
                        <div class="inner-box">
                            <div class="order-info">
                                <h4 class="sub-title">Sepetim</h4>
                                <div class="order-product">
                                    <ul class="order-list clearfix">
                                        <li class="title clearfix">
                                            <p>Ürün</p>
                                            <span>Toplam</span>
                                        </li>
                                        {% for item in cart %}
                                        <li>
                                            <div class="single-box clearfix">
                                                <img src="{% if item.product.image %}{{ item.product.image.url }}{% else %}{% endif %}" alt="">
                                                <h6>{{ item.product }}</h6>
                                                <span>TL {{ item.total_price }}</span>
                                            </div>
                                        </li>
                                        {% endfor %}
                                        <li class="order-total clearfix">
                                            <h6>KDV Dahil Fiyat</h6>
                                            <span>TL {{ cart.get_total_price }}</span>
                                        </li>
                                    </ul>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </section>

{% endblock %}


orders/templates/orders/order/created.html
{% extends "base.html" %}
{% load staticfiles %}
{% block seo %}
<title>Tebrikler Alış Tamamlandı</title>
{% endblock %}

{% block css%}
<style>
    .invoice-box {
        max-width: 800px;
        margin: auto;
        padding: 30px;
        border: 1px solid #eee;
        box-shadow: 0 0 10px rgba(0, 0, 0, .15);
        font-size: 16px;
        line-height: 24px;
        font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
        color: #555;
    }

    .invoice-box table {
        width: 100%;
        line-height: inherit;
        text-align: left;
    }

    .invoice-box table td {
        padding: 5px;
        vertical-align: top;
    }

    .invoice-box table tr td:nth-child(2) {
        text-align: right;
    }

    .invoice-box table tr.top table td {
        padding-bottom: 20px;
    }

    .invoice-box table tr.top table td.title {
        font-size: 45px;
        line-height: 45px;
        color: #333;
    }

    .invoice-box table tr.information table td {
        padding-bottom: 40px;
    }

    .invoice-box table tr.heading td {
        background: #eee;
        border-bottom: 1px solid #ddd;
        font-weight: bold;
    }

    .invoice-box table tr.details td {
        padding-bottom: 20px;
    }

    .invoice-box table tr.item td{
        border-bottom: 1px solid #eee;
    }

    .invoice-box table tr.item.last td {
        border-bottom: none;
    }

    .invoice-box table tr.total td:nth-child(2) {
        border-top: 2px solid #eee;
        font-weight: bold;
    }

    @media only screen and (max-width: 600px) {
        .invoice-box table tr.top table td {
            width: 100%;
            display: block;
            text-align: center;
        }

        .invoice-box table tr.information table td {
            width: 100%;
            display: block;
            text-align: center;
        }
    }

    /** RTL **/
    .rtl {
        direction: rtl;
        font-family: Tahoma, 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
    }

    .rtl table {
        text-align: right;
    }

    .rtl table tr td:nth-child(2) {
        text-align: left;
    }
    </style>
{% endblock %}

{% block content %}

<br>
<div class="invoice-box">
    <div class="media mb-4 invoice-box">
      <img class="d-flex mr-3 rounded-circle" src="{% static 'resimler/shop.PNG' %}" width="100px" height="100px" alt="">
      <div class="media-body">
        <h5 class="mt-0"></h5>
          <h1>Sipariş NO :[{{ order.id }}]</h1> <br>
          <h6>Tşkler Bizi Tercih Ettiğin İçin :)</h6>
      </div>
    </div>
</div>
{{order.first_name}}
{{order.quantity}}
{% endblock %}

orders/templates/orders/order/fail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block seo %}
    <title>Satın Aldıklarım</title>

{% endblock %}
{% block content %}

  <section class="blog-details">
            <div class="auto-container">
                <div class="blog-details-content">
                    <figure class="image-box"><img src="{% static 'red.jpg' %}" alt=""></figure>
                </div>
            </div>
        </section>



{% endblock %}

orders/templates/orders/order/take.html
{% extends "base.html" %}
{% load static %}
{% block seo %}
    <title>Satın Aldıklarım</title>

{% endblock %}
{% block content %}

<div class="small-header bg-img-custom" style="background-image: url('{% static 'banner3.jpg' %}');">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <h2>Ödeme Tamamla</h2>
          </div>
          <div class="col-md-6 text-right">
            <h4 class="breadcrumb"><a href="index.html">Home</a> / <a href="shop.html">Shop</a>
            </h4>
          </div>
        </div>
      </div>
    </div>

<br>
<br>
{% if cart|length > 0.9 %}
<section class="section-small" id="shop">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <h3>Sepetim</h3>
            <table class="table shop-cart table-hover">
              <thead>
                <tr>
                  <td>Product</td>
                  <td>Ürün</td>
                  <td>Toplam</td>
                </tr>
              </thead>
              <tbody>
              {% for item in cart %}
                {% with product=item.product %}
                <tr>
                  <td class="hidden-xs"><img src="{% if product.image %}{{ product.image.url }}{% else %}{% endif %}" alt=""></td>
                  <td>{{product.name}}</td>
                  <td class="hidden-xs">
                    <h4>₺ {{ item.total_price }}</h4>
                  </td>
                </tr>
                {% endwith %}
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div class="col-lg-3 col-lg-offset-1">
            <h3>Genel Toplam</h3>
            <p>Fiyatlarımıza Kdv Dahildir.</p>
            <div class="table-responsive">
              <table class="table">
                <tbody>
                  <tr>
                    <td>Genel Toplam</td>
                    <th>₺  {{ cart.get_total_price }}</th>
                  </tr>
                </tbody>
              </table>
            </div>
            <button class="btn btn-dark" type="submit"><a style="color:white;" href="{%  url 'orders:payment'  %}"> Ödemeyi Tamamla </a></button>
            <hr>
          </div>
        </div>
      </div>
    </section>
{% else %}
<section class="section-small text-center" id="services">
      <div class="container">
        <div class="row">
            <p><a class="button btn btn-dark" href="/shop/dersler/">Hadi Gel Ürünlerimize Bakalım</a></p>
        </div>
      </div>
    </section>
{% endif %}
{% endblock %}